export enum TYPES {
  ADD_TASK = 'ADD_TASK',
  DELETE_TASK = 'DELETE_TASK',
  CHECK_TASK = 'CHECK_TASK',
  EDIT_TASK = 'EDIT_TASK',
  CHANGE_VALUE_TASK = 'CHANGE_VALUE_TASK',
  ONBLUR_TASK = 'ONBLUR_TASK',
  FILTER_ALL = 'FILTER_ALL',
  FILTER_ACTIVE = 'FILTER_ACTIVE',
  FILTER_COMPLETED = 'FILTER_COMPLETED',
  CLEAR_COMPLETED = 'CLEAR_COMPLETED',
  CHECK_ALL = 'CHECK_ALL',
}